#!/usr/bin/env bash
set -Eeuo pipefail

umask 027

APP_ROOT="${APP_ROOT:-/opt/echonote-runtime}"
COMPOSE_FILE="${COMPOSE_FILE:-$APP_ROOT/docker-compose.prod.yml}"
ENV_FILE="${ENV_FILE:-/etc/echonote/echonote.env}"
DEPLOY_CONFIG="${DEPLOY_CONFIG:-/etc/echonote/deploy.conf}"
STATE_DIR="${STATE_DIR:-/var/lib/echonote-deploy}"
STATE_FILE="${STATE_FILE:-$STATE_DIR/current.env}"
LOG_FILE="${LOG_FILE:-/var/log/echonote-deploy.log}"
LOCK_FILE="${LOCK_FILE:-/run/lock/echonote-deploy.lock}"

RUNTIME_IMAGE="${1:-}"
MIGRATE_IMAGE="${2:-}"
RELEASE_ID="${3:-}"

fail() {
  echo "[deploy] ERROR: $*" >&2
  exit 1
}

for command_name in docker curl flock systemctl; do
  command -v "$command_name" >/dev/null 2>&1 || fail "missing command: $command_name"
done

docker compose version >/dev/null 2>&1 || fail "docker compose plugin is unavailable"

[ -f "$DEPLOY_CONFIG" ] || fail "missing deployment config: $DEPLOY_CONFIG"
# This file is root-owned and contains only non-secret deployment policy such
# as ALLOWED_IMAGE_REPOSITORY. It must not be writable by the deploy user.
# shellcheck disable=SC1090
source "$DEPLOY_CONFIG"

: "${ALLOWED_IMAGE_REPOSITORY:?ALLOWED_IMAGE_REPOSITORY is required in $DEPLOY_CONFIG}"

[[ "$ALLOWED_IMAGE_REPOSITORY" =~ ^[a-zA-Z0-9._:/-]+$ ]] \
  || fail "invalid ALLOWED_IMAGE_REPOSITORY"
[[ "$RELEASE_ID" =~ ^[0-9a-f]{7,40}$ ]] || fail "invalid release id"

EXPECTED_RUNTIME_IMAGE="${ALLOWED_IMAGE_REPOSITORY}:sha-${RELEASE_ID}"
EXPECTED_MIGRATE_IMAGE="${ALLOWED_IMAGE_REPOSITORY}:migrate-sha-${RELEASE_ID}"

[ "$RUNTIME_IMAGE" = "$EXPECTED_RUNTIME_IMAGE" ] \
  || fail "runtime image does not match the approved repository and release"
[ "$MIGRATE_IMAGE" = "$EXPECTED_MIGRATE_IMAGE" ] \
  || fail "migration image does not match the approved repository and release"

[ -f "$COMPOSE_FILE" ] || fail "missing compose file: $COMPOSE_FILE"
[ -f "$ENV_FILE" ] || fail "missing environment file: $ENV_FILE"

mkdir -p "$APP_ROOT" "$STATE_DIR" "$(dirname "$LOG_FILE")" "$(dirname "$LOCK_FILE")"
touch "$LOG_FILE" "$LOCK_FILE"
chmod 600 "$LOG_FILE"

exec 9>"$LOCK_FILE"
flock -n 9 || fail "another deployment is already running"

exec > >(tee -a "$LOG_FILE") 2>&1

echo "[deploy] $(date -Is) starting release $RELEASE_ID"
echo "[deploy] runtime image: $RUNTIME_IMAGE"
echo "[deploy] migration image: $MIGRATE_IMAGE"

CURRENT_IMAGE=""
CURRENT_MIGRATE_IMAGE=""
CURRENT_RELEASE_ID=""
if [ -f "$STATE_FILE" ]; then
  # The state file is generated by this root-owned script after validation.
  # shellcheck disable=SC1090
  source "$STATE_FILE"
fi

LEGACY_WEB_ACTIVE=0
LEGACY_WORKER_ACTIVE=0
systemctl is-active --quiet echonote-web && LEGACY_WEB_ACTIVE=1 || true
systemctl is-active --quiet echonote-worker && LEGACY_WORKER_ACTIVE=1 || true

export ECHONOTE_IMAGE="$RUNTIME_IMAGE"
export ECHONOTE_MIGRATE_IMAGE="$MIGRATE_IMAGE"
export ENV_FILE

cd "$APP_ROOT"

echo "[deploy] pulling images while the current release stays online"
docker pull "$RUNTIME_IMAGE"
docker pull "$MIGRATE_IMAGE"

echo "[deploy] validating compose configuration"
docker compose -f "$COMPOSE_FILE" config --quiet

echo "[deploy] applying backward-compatible database migrations"
docker compose -f "$COMPOSE_FILE" run --rm --no-deps migrate

wait_for_health() {
  local attempt
  for attempt in $(seq 1 30); do
    if curl -fsS -o /dev/null --connect-timeout 2 --max-time 5 http://127.0.0.1:3001/login; then
      return 0
    fi
    sleep 2
  done
  return 1
}

restore_previous_release() {
  echo "[deploy] restoring the previous release"
  docker compose -f "$COMPOSE_FILE" stop web worker >/dev/null 2>&1 || true

  if [ -n "$CURRENT_IMAGE" ] && [ -n "$CURRENT_MIGRATE_IMAGE" ]; then
    export ECHONOTE_IMAGE="$CURRENT_IMAGE"
    export ECHONOTE_MIGRATE_IMAGE="$CURRENT_MIGRATE_IMAGE"
    docker compose -f "$COMPOSE_FILE" up -d --no-deps web worker
    wait_for_health || fail "previous container release did not recover"
    echo "[deploy] previous container release restored"
    return
  fi

  if [ "$LEGACY_WEB_ACTIVE" -eq 1 ] || [ "$LEGACY_WORKER_ACTIVE" -eq 1 ]; then
    [ "$LEGACY_WEB_ACTIVE" -eq 1 ] && systemctl start echonote-web
    [ "$LEGACY_WORKER_ACTIVE" -eq 1 ] && systemctl start echonote-worker
    wait_for_health || fail "legacy systemd release did not recover"
    echo "[deploy] legacy systemd release restored"
    return
  fi

  fail "no previous release is available for automatic recovery"
}

echo "[deploy] switching application processes"
[ "$LEGACY_WEB_ACTIVE" -eq 1 ] && systemctl stop echonote-web
[ "$LEGACY_WORKER_ACTIVE" -eq 1 ] && systemctl stop echonote-worker

if ! docker compose -f "$COMPOSE_FILE" up -d --no-deps web worker; then
  restore_previous_release
  fail "new containers failed to start"
fi

if ! wait_for_health; then
  restore_previous_release
  fail "new release failed the direct web health check"
fi

if ! curl -fsS -o /dev/null --connect-timeout 3 --max-time 8 http://127.0.0.1:8081/login; then
  restore_previous_release
  fail "new release failed the nginx health check"
fi

if [ "$LEGACY_WEB_ACTIVE" -eq 1 ] || [ "$LEGACY_WORKER_ACTIVE" -eq 1 ]; then
  echo "[deploy] disabling legacy systemd services after successful cutover"
  systemctl disable echonote-web echonote-worker
fi

runtime_digest="$(docker image inspect --format '{{index .RepoDigests 0}}' "$RUNTIME_IMAGE" 2>/dev/null || true)"

state_tmp="$(mktemp "$STATE_DIR/current.env.XXXXXX")"
{
  printf 'CURRENT_IMAGE=%q\n' "$RUNTIME_IMAGE"
  printf 'CURRENT_MIGRATE_IMAGE=%q\n' "$MIGRATE_IMAGE"
  printf 'CURRENT_RELEASE_ID=%q\n' "$RELEASE_ID"
} >"$state_tmp"
chmod 600 "$state_tmp"
mv -f "$state_tmp" "$STATE_FILE"

echo "[deploy] runtime digest: ${runtime_digest:-unknown}"
echo "[deploy] $(date -Is) release $RELEASE_ID is healthy"
